{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMQXITJ964fCh6uqFU9Ugsm"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "!pip install gymnasium pybullet"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "iy79vb_cjdT0",
        "outputId": "d0b9b1d0-05e0-4529-ba54-6f591c4fd5b2"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: gymnasium in /usr/local/lib/python3.12/dist-packages (1.2.1)\n",
            "Requirement already satisfied: pybullet in /usr/local/lib/python3.12/dist-packages (3.2.7)\n",
            "Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium) (2.0.2)\n",
            "Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium) (3.1.1)\n",
            "Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium) (4.15.0)\n",
            "Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from gymnasium) (0.0.4)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import gymnasium as gym\n",
        "from gymnasium import spaces\n",
        "import numpy as np\n",
        "import pybullet as p\n",
        "import pybullet_data\n",
        "import time\n",
        "from stable_baselines3 import PPO\n",
        "import matplotlib.pyplot as plt\n",
        "from IPython.display import clear_output"
      ],
      "metadata": {
        "id": "2lxggi_2EYnO"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "class CupGraspingEnv(gym.Env):\n",
        "    \"\"\"\n",
        "    PyBullet KUKA 로봇팔로 컵을 잡는 강화학습 환경\n",
        "    'gym.Env'를 상속받아, AI가 알아들을 수 있는 표준 규격 만듦\n",
        "    \"\"\"\n",
        "    def __init__(self):\n",
        "        super(CupGraspingEnv, self).__init__()\n",
        "        self.client = p.connect(p.DIRECT)\n",
        "        p.setAdditionalSearchPath(pybullet_data.getDataPath())\n",
        "\n",
        "        # --- AI에게 '게임의 규칙'을 알려줌 ---\n",
        "        # Action Space: AI가 할 수 있는 행동의 종류와 범위 정의\n",
        "        action_bound = 0.1 # 한 스텝에 최대 0.1m 이동\n",
        "        self.action_space = spaces.Box(low=-action_bound, high=action_bound, shape=(3,), dtype=np.float32)\n",
        "\n",
        "        # Observation Space: 그리퍼(3), 컵(3), 관절각도(7) -> 총 13차원\n",
        "        obs_dim = 3 + 3 + 7\n",
        "        obs_low = np.array([-np.inf] * obs_dim)\n",
        "        obs_high = np.array([np.inf] * obs_dim)\n",
        "        self.observation_space = spaces.Box(low=obs_low, high=obs_high, dtype=np.float32)\n",
        "\n",
        "\n",
        "        # 클래스 내부에서 사용할 변수들을 초기화\n",
        "        self.robotId = None\n",
        "        self.cupId = None\n",
        "        self.end_effector_index = 6\n",
        "        self.distance_to_cup = 0\n",
        "        self.max_steps_per_episode = 200 # 한 에피소드의 최대 스텝 수\n",
        "        self.step_counter = 0\n",
        "\n",
        "    def reset(self, seed=None, options=None):\n",
        "        self.step_counter = 0 # 스텝 카운터 초기화\n",
        "        # PyBullet 세상 초기화\n",
        "        p.resetSimulation(physicsClientId=self.client)\n",
        "        p.setGravity(0, 0, -9.8)\n",
        "\n",
        "        #  바닥, 로봇, 컵 구성\n",
        "        p.loadURDF(\"plane.urdf\")\n",
        "        self.robotId = p.loadURDF(\"kuka_iiwa/model.urdf\", [0, 0, 0], useFixedBase=True)\n",
        "        cup_start_pos = [0.5, 0.2, 0.05]\n",
        "        cup_visual_shape = p.createVisualShape(p.GEOM_CYLINDER, radius=0.04, length=0.1, rgbaColor=[0.8, 0.2, 0.2, 1])\n",
        "        cup_collision_shape = p.createCollisionShape(p.GEOM_CYLINDER, radius=0.04, height=0.1)\n",
        "        self.cupId = p.createMultiBody(baseMass=0.1, baseCollisionShapeIndex=cup_collision_shape, baseVisualShapeIndex=cup_visual_shape, basePosition=cup_start_pos)\n",
        "\n",
        "        # 첫 번째 상태 관측 및 초기 거리 계산\n",
        "        observation = self._get_obs()\n",
        "        self.distance_to_cup = np.linalg.norm(self.gripper_pos - self.cup_pos)\n",
        "        self.initial_distance = np.linalg.norm(self.gripper_pos - self.cup_pos)\n",
        "        info = {}\n",
        "        return observation, info\n",
        "\n",
        "    def step(self, action):\n",
        "        # 1. 현재 그리퍼 위치 파악\n",
        "        current_gripper_state = p.getLinkState(self.robotId, self.end_effector_index)\n",
        "        current_gripper_pos = np.array(current_gripper_state[0])\n",
        "\n",
        "        # 2. AI가 준 action을 바탕으로 목표 위치 계산\n",
        "        target_position = current_gripper_pos + action\n",
        "\n",
        "        # 3. 역기구학 계산\n",
        "        target_joint_angles = p.calculateInverseKinematics(self.robotId, self.end_effector_index, target_position)\n",
        "\n",
        "        # 4. 로봇 제어 명령\n",
        "        p.setJointMotorControlArray(\n",
        "            bodyIndex=self.robotId,\n",
        "            jointIndices=range(p.getNumJoints(self.robotId)),\n",
        "            controlMode=p.POSITION_CONTROL,\n",
        "            targetPositions=target_joint_angles\n",
        "        )\n",
        "\n",
        "        p.stepSimulation()\n",
        "\n",
        "        # 5. 다음 상태, 보상, 종료 여부 계산\n",
        "        observation = self._get_obs()\n",
        "        reward = self._compute_reward()\n",
        "        terminated = self._check_done()\n",
        "        info = {}\n",
        "\n",
        "        # 6. AI에게 결과 보고\n",
        "        return observation, reward, terminated, False, info\n",
        "\n",
        "    def _get_obs(self):\n",
        "        # --- 👇 상태(State) 정보 추가 ---\n",
        "        gripper_state = p.getLinkState(self.robotId, self.end_effector_index)\n",
        "        self.gripper_pos = np.array(gripper_state[0])\n",
        "\n",
        "        cup_pos, _ = p.getBasePositionAndOrientation(self.cupId)\n",
        "        self.cup_pos = np.array(cup_pos)\n",
        "\n",
        "        # 로봇의 모든 관절 각도를 상태 정보에 추가합니다.\n",
        "        joint_states = p.getJointStates(self.robotId, range(p.getNumJoints(self.robotId)))\n",
        "        joint_positions = [state[0] for state in joint_states]\n",
        "\n",
        "        # 그리퍼 위치, 컵 위치, 관절 각도를 모두 합쳐서 반환합니다.\n",
        "        observation = np.concatenate([self.gripper_pos, self.cup_pos, joint_positions])\n",
        "        return observation\n",
        "\n",
        "    def _compute_reward(self):\n",
        "        # 1. 행동 이후의 새로운 거리를 계산\n",
        "        new_distance = np.linalg.norm(self.gripper_pos - self.cup_pos)\n",
        "\n",
        "        # 2. '거리의 변화량'을 기본 보상\n",
        "        #    이전 거리(self.distance_to_cup)보다 가까워졌으면 플러스 보상, 멀어졌으면 마이너스 보상이 됩니다.\n",
        "        reward = (self.distance_to_cup - new_distance) * 100\n",
        "\n",
        "        # 3. 다음 스텝에서의 계산을 위해, 현재 거리를 '이전 거리'로 저장\n",
        "        self.distance_to_cup = new_distance\n",
        "\n",
        "        # 4. 성공 보상\n",
        "        if new_distance < 0.05:\n",
        "            reward += 1000\n",
        "\n",
        "        # 5. 실패 페널티\n",
        "        cup_pos, cup_orn = p.getBasePositionAndOrientation(self.cupId)\n",
        "        cup_euler = p.getEulerFromQuaternion(cup_orn)\n",
        "        if abs(cup_euler[0]) > 0.5 or abs(cup_euler[1]) > 0.5:\n",
        "            reward -= 500\n",
        "\n",
        "        return reward\n",
        "\n",
        "    def _check_done(self):\n",
        "        current_distance = np.linalg.norm(self.gripper_pos - self.cup_pos)\n",
        "\n",
        "        # 1. 성공 조건\n",
        "        if current_distance < 0.05:\n",
        "            print(\"성공! 컵에 도달했습니다.\")\n",
        "            return True\n",
        "\n",
        "        # 2. 실패 조건\n",
        "        cup_pos, cup_orn = p.getBasePositionAndOrientation(self.cupId)\n",
        "        cup_euler = p.getEulerFromQuaternion(cup_orn)\n",
        "        if abs(cup_euler[0]) > 0.5 or abs(cup_euler[1]) > 0.5:\n",
        "            print(\"실패! 컵을 넘어뜨렸습니다.\")\n",
        "            return True\n",
        "\n",
        "        # 3. 시간 초과 조건\n",
        "        self.step_counter += 1\n",
        "        if self.step_counter > self.max_steps_per_episode:\n",
        "            print(\"시간 초과! 리셋합니다.\")\n",
        "            return True\n",
        "\n",
        "        return False\n",
        "\n",
        "    def render(self):\n",
        "        \"\"\" Colab에서 시각적으로 확인하기 위한 렌더링 함수 \"\"\"\n",
        "        view_matrix = p.computeViewMatrix(cameraEyePosition=[1,1,1], cameraTargetPosition=[0.5,0,0.5], cameraUpVector=[0,0,1])\n",
        "        proj_matrix = p.computeProjectionMatrixFOV(fov=60.0, aspect=1.0, nearVal=0.1, farVal=100.0)\n",
        "        (w, h, rgb, _, _) = p.getCameraImage(width=224, height=224, viewMatrix=view_matrix, projectionMatrix=proj_matrix)\n",
        "        return rgb\n",
        "\n",
        "    def close(self):\n",
        "        if self.client >= 0:\n",
        "            p.disconnect(self.client)\n",
        "            self.client = -1 # 연결이 끊겼음을 표시\n",
        "        print(\"PyBullet 시뮬레이션 연결이 종료되었습니다.\")"
      ],
      "metadata": {
        "id": "u_DbfCUuo7zt"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}